apiVersion: gpte.opentlc.com/v1alpha1
kind: Nexus
metadata:
  name: example-nexus
spec:
  nexusVolumeSize: 10Gi
  nexusSsl: True
  nexusImageTag: latest
  nexusCpuRequest: 1
  nexusCpuLimit: 2
  nexusMemoryRequest: 2Gi
  nexusMemoryLimit: 2Gi