apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nexus-operator
  template:
    metadata:
      labels:
        name: nexus-operator
    spec:
      serviceAccountName: nexus-operator
      containers:
        - name: nexus-operator
          # Replace this with the built image name
          image: quay.io/wkulhanek/nexus-operator:v0.0.6
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "nexus-operator"
