apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nexus-operator
  template:
    metadata:
      labels:
        name: nexus-operator
    spec:
      serviceAccountName: nexus-operator
      containers:
        - name: nexus-operator
          image: quay.io/wkulhanek/nexus-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "nexus-operator"
