---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nexus-operator
  template:
    metadata:
      labels:
        name: nexus-operator
    spec:
      serviceAccountName: nexus-operator
      containers:
      - name: nexus-operator
        image: quay.io/gpte-devops-automation/nexus-operator:v0.17
        imagePullPolicy: "Always"
        volumeMounts:
        - mountPath: /tmp/ansible-operator/runner
          name: runner
        env:
        - name: WATCH_NAMESPACE
          value: ""
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: "nexus-operator"
        - name: ANSIBLE_GATHERING
          value: explicit
      volumes:
      - name: runner
        emptyDir: {}
